### ISSUE TITLE
Doesn't take directory in account

### ISSUE THREAD

**Issue by lbcd** [AvaiBookSports/DoctrineMigrationsMultipleDatabaseBundle#19]
Hello

Thanks for this bundle that seems to be great. 
I have an issue when I use it. 

Here is my configuration: 
```
doctrine:
    dbal:
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
            bordereau:
                url: '%env(resolve:DATABASE_BORDEREAU_URL)%'
        default_connection: default
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                auto_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
            bordereau:
                connection: bordereau
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Bordereau:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Bordereau'
                        prefix: 'App\Entity\Bordereau'
                        alias: Bordereau
```

```
doctrine_migrations:
    em: default
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        DoctrineMigrations: '%kernel.project_dir%/migrations/gli-agrement'
```

```
doctrine_migrations_multiple_database:
    entity_managers:
        default:
            migrations_paths:
                DoctrineMigrations\GliAgrement: '%kernel.project_dir%/migrations/gli-agrement'
        bordereau:
            migrations_paths:
                DoctrineMigrations\Bordereau: '%kernel.project_dir%/migrations/bordereau'
```

It seems to be good for me but when I make a `bin/console doctrine:m:diff -v --em=bordereau` it put a file in  '%kernel.project_dir%/migrations/gli-agrement' while it suppose to put it in `bordereau` directory.

Diff content file is ok. It is only concerne Bordereau entities.

Another issue when I launch `bin/console doctrine:m:m  -v --em=bordereau` it try to play '%kernel.project_dir%/migrations/gli-agrement' migrations in my bordereau database.
It seems that it doesn't take migrations_paths information in account.
