### ISSUE TITLE
Migrations applied to wrong entity/database

### ISSUE THREAD

**Issue by mattsbennett** [AvaiBookSports/DoctrineMigrationsMultipleDatabaseBundle#9]
I think I'm missing something trying to use this package. My config is like the example:
```
doctrine_migrations_multiple_database:
    entity_managers:
        archive:
            migrations_paths:
                'App\Archive\Migrations': '%kernel.project_dir%/migrations/Archive'
            services:
                'Doctrine\Migrations\Version\MigrationFactory': 'App\Doctrine\Service\MigrationFactory'
        default:
            migrations_paths:
                'App\Main\Migrations': '%kernel.project_dir%/migrations/Default'
            services:
                'Doctrine\Migrations\Version\MigrationFactory': 'App\Doctrine\Service\MigrationFactory'
        ...
```

However, unless I also include a `doctrine_migrations.yaml` file with all of my different paths under `migration_paths` there, I get a "No migrations found" error. And when I _do_ include that file, my default entity manager/connection is used regardless  of what I pass in the `--em` option.

Using the following with symfony 4:

```
        "avaibooksports/doctrine-migrations-multiple-database-bundle": "^0.3.3",
        "doctrine/doctrine-migrations-bundle": "^3.2",
        "doctrine/migrations": "^3.5",
```

**Comment by devnix** [comment]
I'm not very sure about what can be wrong. I can provide you a working configuration so you can compare and try:

```yaml
# doctrine.yaml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                server_version: mariadb-10.1.26
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                mapping_types:
                    enum: string
            geonames:
                url: '%env(resolve:GEONAMES_DATABASE_URL)%'
                server_version: mariadb-10.1.26
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                mapping_types:
                    enum: string

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Main:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/App/Entity/Main'
                        prefix: 'App\Entity\Main'
                        alias: Main
            geonames:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                connection: geonames
                mappings:
                    Geonames:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/App/Entity/Geonames'
                        prefix: 'App\Entity\Geonames'
                        alias: Geonames
```

```yaml
# doctrine_migrations.yaml
doctrine_migrations:
    em: default
    migrations_paths:
        DoctrineMigrations: '%kernel.project_dir%/migrations/Main'
```

```yaml
# doctrine_migrations_multiple_database.yaml
doctrine_migrations_multiple_database:
    entity_managers:
        default:
            migrations_paths:
                DoctrineMigrations\Main: '%kernel.project_dir%/migrations/Main'
        geonames:
            migrations_paths:
                DoctrineMigrations\Geonames: '%kernel.project_dir%/migrations/Geonames'
```

Let me know if it helps!
